apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ui-middleware
  labels:
    release: kube-prom
spec:
  endpoints:
    - path: /metrics
      port: monitoring
  selector:
    matchLabels:
      grafana.ox.io/service-monitor-implementation: default
